export { DashboardKpis } from './DashboardKpis'
export { QueueOverviewWidget } from './QueueOverviewWidget'
export { RecommendationsWidget } from './RecommendationsWidget'
export { RecentCallsWidget } from './RecentCallsWidget'
export { RoomLoadWidget } from './RoomLoadWidget'
